# Prompts Module
# Centralized location for all LLM prompts

from prompts.chain_of_thought import COT_REASONING_TEMPLATE, COT_SYSTEM_PROMPT
from prompts.generate_response import (
    CLARIFICATION_INSTRUCTION,
    FEW_SHOT_EXAMPLES,
    SYSTEM_PROMPT_TEMPLATE,
)
from prompts.query_refinement_prompts import (
    REFINEMENT_SYSTEM_PROMPT,
    REFINEMENT_PROMPT_TEMPLATE,
)
from prompts.synthesis_prompts import (
    SYNTHESIS_SYSTEM_PROMPT,
    SYNTHESIS_PROMPT_TEMPLATE,
)
from prompts.memory_extraction_prompts import (
    FACT_EXTRACTION_SYSTEM_PROMPT,
    FACT_EXTRACTION_USER_PROMPT_TEMPLATE,
    SKIP_FACT_EXTRACTION_INTENTS,
)
from prompts.evaluation_prompts import FAITHFULNESS_EVALUATION_PROMPT
from prompts.kg_extraction_prompts import (
    KG_EXTRACTION_SYSTEM_PROMPT,
    KG_EXTRACTION_PROMPT_TEMPLATE,
)
from prompts.routing_prompts import ROUTING_PROMPT_TEMPLATE, SOURCE_DESCRIPTIONS

__all__ = [
    "COT_SYSTEM_PROMPT",
    "COT_REASONING_TEMPLATE",
    "FEW_SHOT_EXAMPLES",
    "SYSTEM_PROMPT_TEMPLATE",
    "CLARIFICATION_INSTRUCTION",
    "REFINEMENT_SYSTEM_PROMPT",
    "REFINEMENT_PROMPT_TEMPLATE",
    "SYNTHESIS_SYSTEM_PROMPT",
    "SYNTHESIS_PROMPT_TEMPLATE",
    "FACT_EXTRACTION_SYSTEM_PROMPT",
    "FACT_EXTRACTION_USER_PROMPT_TEMPLATE",
    "SKIP_FACT_EXTRACTION_INTENTS",
    "FAITHFULNESS_EVALUATION_PROMPT",
    "KG_EXTRACTION_SYSTEM_PROMPT",
    "KG_EXTRACTION_PROMPT_TEMPLATE",
    "ROUTING_PROMPT_TEMPLATE",
    "SOURCE_DESCRIPTIONS",
]
